import React, { useCallback, useEffect, useMemo, useState } from 'react'; import { CalendarClock } from 'lucide-react'; import { Link } from 'react-router-dom'; import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext'; import { Badge } from '../../components/ui/badge'; import { Button } from '../../components/ui/button'; import { Card, CardContent } from '../../components/ui/card'; import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog'; import { Input } from '../../components/ui/input'; import { Label } from '../../components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { apiError, ErrorState, formatDate, getId, LoadingState, MenuVibesPage, unwrapList, unwrapStages } from './shared';
export const MenuVibesPipelinePage=()=>{const {api,user}=useAuth();const [items,setItems]=useState([]);const [stages,setStages]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [moving,setMoving]=useState(null);const [follow,setFollow]=useState({next_action:'',next_action_at:''});const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [p,s]=await Promise.all([api.get('/menuvibes/prospects'),api.get('/menuvibes/pipeline/config')]);setItems(unwrapList(p.data,'prospects'));setStages(unwrapStages(s.data));}catch(e){setError(apiError(e,'No se pudo cargar el pipeline.'));}finally{setLoading(false);}},[api]);useEffect(()=>{load();},[load]);
 const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s.key,items.filter(i=>i.stage===s.key)])),[items,stages]);
 const requestMove=(item,stage)=>{if(stage===item.stage)return;const target=stages.find(s=>s.key===stage);if(target?.requires_next_action&&stage!=='new'){setMoving({item,stage});setFollow({next_action:item.next_action||'',next_action_at:item.next_action_at?new Date(item.next_action_at).toISOString().slice(0,16):''});}else move(item,stage,{});};
 const move=async(item,stage,extra)=>{setSaving(true);try{await api.patch(`/menuvibes/prospects/${getId(item)}`,{stage,assigned_to:item.assigned_to||user?.id||user?.user_id,...extra});toast.success('Prospecto movido');setMoving(null);load();}catch(e){toast.error(apiError(e,'No se pudo cambiar la etapa.'));}finally{setSaving(false);}};
 return <MenuVibesPage title="Pipeline" description="Flujo comercial de restaurantes, desde investigación hasta cierre.">{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:<div className="overflow-x-auto pb-4"><div className="flex min-w-max gap-4">{stages.map(stage=><section key={stage.key} className="w-72 rounded-xl border bg-muted/20"><header className="flex items-center justify-between border-b p-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{backgroundColor:stage.color}}/><h2 className="font-semibold">{stage.label}</h2></div><Badge variant="outline">{grouped[stage.key]?.length||0}</Badge></header><div className="space-y-3 p-3">{grouped[stage.key]?.map(item=><Card key={getId(item)}><CardContent className="p-4"><Link to={`/menuvibes/prospects/${getId(item)}`} className="font-semibold hover:text-primary">{item.business_name}</Link><p className="mt-1 text-xs text-muted-foreground">{item.contact_name||item.city||'Datos por completar'}</p><p className="my-3 flex items-center gap-1 text-xs text-muted-foreground"><CalendarClock className="h-3 w-3"/>{formatDate(item.next_action_at)}</p><Select value={item.stage} onValueChange={value=>requestMove(item,value)}><SelectTrigger className="h-8 text-xs"><SelectValue/></SelectTrigger><SelectContent>{stages.map(s=><SelectItem key={s.key} value={s.key}>{s.label}</SelectItem>)}</SelectContent></Select></CardContent></Card>)}{!grouped[stage.key]?.length&&<p className="py-8 text-center text-xs text-muted-foreground">Sin prospectos</p>}</div></section>)}</div></div>}
 <Dialog open={!!moving} onOpenChange={open=>!open&&setMoving(null)}><DialogContent><DialogHeader><DialogTitle>Programa el seguimiento</DialogTitle></DialogHeader><div className="space-y-4 py-3"><div><Label>Siguiente acción</Label><Input className="mt-1" value={follow.next_action} onChange={e=>setFollow(p=>({...p,next_action:e.target.value}))}/></div><div><Label>Fecha y hora</Label><Input className="mt-1" type="datetime-local" value={follow.next_action_at} onChange={e=>setFollow(p=>({...p,next_action_at:e.target.value}))}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setMoving(null)}>Cancelar</Button><Button disabled={saving||!follow.next_action||!follow.next_action_at} onClick={()=>move(moving.item,moving.stage,{next_action:follow.next_action,next_action_at:new Date(follow.next_action_at).toISOString()})}>Mover prospecto</Button></DialogFooter></DialogContent></Dialog>
 </MenuVibesPage>;
};
