import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, Search, Store } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { Badge } from '../../components/ui/badge'; import { Button } from '../../components/ui/button';
import { Card, CardContent } from '../../components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input'; import { Label } from '../../components/ui/label';
import { Textarea } from '../../components/ui/textarea';
import { apiError, ErrorState, formatDate, getId, LoadingState, MenuVibesPage, unwrapList } from './shared';

const EMPTY = { business_name: '', contact_name: '', phone: '', email: '', city: '', zone: '', business_type: 'restaurant', source: 'manual', website_url: '', instagram_url: '', next_action: '', next_action_at: '', notes: '' };
export const MenuVibesProspectsPage = () => {
 const { api, user } = useAuth(); const navigate = useNavigate(); const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [search,setSearch]=useState(''); const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [form,setForm]=useState(EMPTY);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await api.get('/menuvibes/prospects',{params:search.trim()?{search:search.trim()}:undefined});setItems(unwrapList(response.data,'prospects'));}catch(e){setError(apiError(e,'No se pudieron cargar los prospectos.'));}finally{setLoading(false);}},[api,search]);
 useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer);},[load]);
 const update=(key,value)=>setForm(prev=>({...prev,[key]:value}));
 const submit=async(e)=>{e.preventDefault();setSaving(true);try{const payload=Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''));payload.assigned_to=user?.id||user?.user_id;if(payload.next_action_at)payload.next_action_at=new Date(payload.next_action_at).toISOString();const response=await api.post('/menuvibes/prospects',payload);toast.success('Prospecto creado');setOpen(false);setForm(EMPTY);navigate(`/menuvibes/prospects/${getId(response.data)}`);}catch(err){toast.error(apiError(err,'No se pudo crear el prospecto.'));}finally{setSaving(false);}};
 const content=useMemo(()=>items.map(item=><Link key={getId(item)} to={`/menuvibes/prospects/${getId(item)}`} className="block"><Card className="transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-md"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.business_name}</p><p className="mt-1 text-sm text-muted-foreground">{item.contact_name||'Contacto pendiente'} · {item.city||item.zone||'Ubicación pendiente'}</p></div><Badge variant="secondary" className="capitalize">{String(item.stage||'new').replaceAll('_',' ')}</Badge></div><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>{item.source||'Sin fuente'}</span><span>Próxima: {formatDate(item.next_action_at)}</span></div></CardContent></Card></Link>),[items]);
 return <MenuVibesPage title="Prospectos" description="Restaurantes y ubicaciones en seguimiento comercial." action={<Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Nuevo prospecto</Button>}><div className="relative max-w-xl"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar restaurante, contacto o ciudad…"/></div>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:items.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{content}</div>:<Card><CardContent className="flex flex-col items-center py-14 text-center"><Store className="mb-3 h-9 w-9 text-muted-foreground"/><p className="font-medium">No hay prospectos</p><p className="text-sm text-muted-foreground">Crea el primer restaurante para iniciar el seguimiento.</p></CardContent></Card>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><form onSubmit={submit}><DialogHeader><DialogTitle>Nuevo prospecto</DialogTitle><DialogDescription>Registra una ubicación y su siguiente acción comercial.</DialogDescription></DialogHeader><div className="grid gap-4 py-5 sm:grid-cols-2">{[['business_name','Restaurante *'],['contact_name','Contacto'],['phone','Teléfono'],['email','Email'],['city','Ciudad'],['zone','Zona'],['business_type','Tipo de negocio'],['source','Fuente'],['website_url','Sitio web'],['instagram_url','Instagram'],['next_action','Siguiente acción']].map(([key,label])=><div key={key} className={key==='next_action'?'sm:col-span-2':''}><Label htmlFor={key}>{label}</Label><Input id={key} required={key==='business_name'} value={form[key]} onChange={e=>update(key,e.target.value)} className="mt-1"/></div>)}<div className="sm:col-span-2"><Label htmlFor="next_action_at">Fecha de siguiente acción</Label><Input id="next_action_at" type="datetime-local" value={form.next_action_at} onChange={e=>update('next_action_at',e.target.value)} className="mt-1"/></div><div className="sm:col-span-2"><Label htmlFor="notes">Notas</Label><Textarea id="notes" value={form.notes} onChange={e=>update('notes',e.target.value)} className="mt-1"/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving}>{saving?'Guardando…':'Crear prospecto'}</Button></DialogFooter></form></DialogContent></Dialog>
 </MenuVibesPage>;
};
