import React, { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, ExternalLink, Mail, MapPin, MessageSquarePlus, Phone } from 'lucide-react';
import { Link, useParams } from 'react-router-dom'; import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext'; import { Badge } from '../../components/ui/badge'; import { Button } from '../../components/ui/button'; import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card'; import { Input } from '../../components/ui/input'; import { Label } from '../../components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select'; import { Textarea } from '../../components/ui/textarea';
import { apiError, ErrorState, formatDate, LoadingState, MenuVibesPage, toLocalInput, unwrapList, unwrapStages } from './shared';
const TYPES=[['note','Nota'],['call','Llamada'],['whatsapp','WhatsApp'],['email','Email'],['meeting','Reunión']];
export const MenuVibesProspectDetailPage=()=>{const {id}=useParams();const {api,user}=useAuth();const [item,setItem]=useState(null);const [activities,setActivities]=useState([]);const [stages,setStages]=useState([]);const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [activity,setActivity]=useState({type:'note',summary:''});
 const load=useCallback(async()=>{setError('');try{const [prospectRes,activityRes,stageRes]=await Promise.all([api.get(`/menuvibes/prospects/${id}`),api.get(`/menuvibes/prospects/${id}/activities`),api.get('/menuvibes/pipeline/config')]);setItem(prospectRes.data);setActivities(unwrapList(activityRes.data,'activities'));setStages(unwrapStages(stageRes.data));}catch(e){setError(apiError(e,'No se pudo cargar el prospecto.'));}},[api,id]);useEffect(()=>{load();},[load]);
 const patch=async(payload,message='Cambios guardados')=>{setSaving(true);try{const res=await api.patch(`/menuvibes/prospects/${id}`,payload);setItem(res.data);toast.success(message);}catch(e){toast.error(apiError(e,'No se pudieron guardar los cambios.'));}finally{setSaving(false);}};
 const addActivity=async(e)=>{e.preventDefault();if(!activity.summary.trim())return;setSaving(true);try{await api.post(`/menuvibes/prospects/${id}/activities`,activity);setActivity({type:'note',summary:''});toast.success('Actividad registrada');load();}catch(err){toast.error(apiError(err,'No se pudo registrar la actividad.'));}finally{setSaving(false);}};
 if(!item&&!error)return <MenuVibesPage title="Prospecto"><LoadingState/></MenuVibesPage>;
 return <MenuVibesPage title={item?.business_name||'Prospecto'} description="Ficha comercial, siguiente acción e historial de contacto." action={<Button variant="outline" asChild><Link to="/menuvibes/prospects"><ArrowLeft className="mr-2 h-4 w-4"/>Volver</Link></Button>}>{error?<ErrorState message={error} onRetry={load}/>:<div className="grid gap-6 xl:grid-cols-[1fr_1.25fr]">
 <div className="space-y-6"><Card><CardHeader><div className="flex items-center justify-between"><CardTitle>Datos del restaurante</CardTitle><Badge>{stages.find(s=>s.key===item.stage)?.label||item.stage}</Badge></div></CardHeader><CardContent className="space-y-3 text-sm"><p className="flex gap-2"><MapPin className="h-4 w-4 text-muted-foreground"/>{item.city||'Ciudad pendiente'} {item.zone&&`· ${item.zone}`}</p><p className="flex gap-2"><Phone className="h-4 w-4 text-muted-foreground"/>{item.phone||'Teléfono pendiente'}</p><p className="flex gap-2"><Mail className="h-4 w-4 text-muted-foreground"/>{item.email||'Email pendiente'}</p>{[item.website_url,item.instagram_url,item.google_maps_url].filter(Boolean).map(url=><a key={url} className="flex gap-2 text-primary hover:underline" href={url} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4"/>{url}</a>)}{item.notes&&<p className="rounded-lg bg-muted p-3 whitespace-pre-wrap">{item.notes}</p>}</CardContent></Card>
 <Card><CardHeader><CardTitle>Etapa y seguimiento</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Etapa</Label><Select value={item.stage} onValueChange={stage=>patch({stage,assigned_to:item.assigned_to||user?.id||user?.user_id,next_action:item.next_action||undefined,next_action_at:item.next_action_at||undefined},'Etapa actualizada')} disabled={saving}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{stages.map(s=><SelectItem key={s.key} value={s.key}>{s.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Siguiente acción</Label><Input className="mt-1" defaultValue={item.next_action||''} onBlur={e=>e.target.value!==item.next_action&&patch({next_action:e.target.value||null})}/></div><div><Label>Fecha</Label><Input className="mt-1" type="datetime-local" defaultValue={toLocalInput(item.next_action_at)} onBlur={e=>patch({next_action_at:e.target.value?new Date(e.target.value).toISOString():null})}/></div><p className="text-xs text-muted-foreground">Última interacción: {formatDate(item.last_interaction_at,true)}</p></CardContent></Card></div>
 <div className="space-y-6"><Card><CardHeader><CardTitle className="flex gap-2"><MessageSquarePlus className="h-5 w-5"/>Registrar actividad</CardTitle></CardHeader><CardContent><form onSubmit={addActivity} className="space-y-3"><Select value={activity.type} onValueChange={type=>setActivity(p=>({...p,type}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{TYPES.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select><Textarea value={activity.summary} onChange={e=>setActivity(p=>({...p,summary:e.target.value}))} placeholder="Resumen de la conversación o nota…"/><Button disabled={saving||!activity.summary.trim()}>Registrar</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Historial</CardTitle></CardHeader><CardContent className="space-y-3">{activities.length?activities.map((a,index)=><div key={a.id||index} className="border-l-2 border-primary/30 pl-4"><div className="flex justify-between gap-2"><p className="font-medium capitalize">{a.type}</p><span className="text-xs text-muted-foreground">{formatDate(a.occurred_at||a.created_at,true)}</span></div><p className="mt-1 text-sm whitespace-pre-wrap">{a.summary}</p></div>):<p className="py-6 text-center text-sm text-muted-foreground">Sin actividades todavía.</p>}</CardContent></Card></div>
 </div>}</MenuVibesPage>;
};
