import React, { useCallback, useEffect, useMemo, useState } from 'react'; import { ExternalLink, Plus, Presentation } from 'lucide-react'; import { Link } from 'react-router-dom'; import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext'; import { Badge } from '../../components/ui/badge'; import { Button } from '../../components/ui/button'; import { Card, CardContent } from '../../components/ui/card'; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../components/ui/dialog'; import { Input } from '../../components/ui/input'; import { Label } from '../../components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select'; import { Textarea } from '../../components/ui/textarea';
import { apiError, DEMO_STATUSES, ErrorState, formatDate, getId, LoadingState, MenuVibesPage, unwrapList } from './shared';
const EMPTY={prospect_id:'',slug:'',url:'',status:'requested',source_type:'manual',source_reference:'',notes:''};
export const MenuVibesDemosPage=()=>{const {api}=useAuth();const [demos,setDemos]=useState([]);const [prospects,setProspects]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [open,setOpen]=useState(false);const [form,setForm]=useState(EMPTY);const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [d,p]=await Promise.all([api.get('/menuvibes/demos'),api.get('/menuvibes/prospects')]);setDemos(unwrapList(d.data,'demos'));setProspects(unwrapList(p.data,'prospects'));}catch(e){setError(apiError(e,'No se pudieron cargar las demos.'));}finally{setLoading(false);}},[api]);useEffect(()=>{load();},[load]);const names=useMemo(()=>Object.fromEntries(prospects.map(p=>[getId(p),p.business_name])),[prospects]);
 const submit=async(e)=>{e.preventDefault();setSaving(true);try{await api.post('/menuvibes/demos',Object.fromEntries(Object.entries(form).filter(([,v])=>v!=='')));toast.success('Demo registrada');setOpen(false);setForm(EMPTY);load();}catch(err){toast.error(apiError(err,'No se pudo registrar la demo.'));}finally{setSaving(false);}};
 const setStatus=async(demo,status)=>{try{await api.patch(`/menuvibes/demos/${getId(demo)}`,{status});toast.success('Estado actualizado');load();}catch(e){toast.error(apiError(e,'No se pudo actualizar la demo.'));}};
 return <MenuVibesPage title="Demos" description="Referencias verificadas para presentar la experiencia MenuVibes." action={<Button onClick={()=>setOpen(true)}><Plus className="mr-2 h-4 w-4"/>Nueva demo</Button>}>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:demos.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{demos.map(d=><Card key={getId(d)}><CardContent className="p-5"><div className="flex justify-between gap-2"><div><p className="font-semibold">{names[d.prospect_id]||d.slug||'Demo'}</p><p className="mt-1 text-xs text-muted-foreground">Verificada: {formatDate(d.last_verified_at)}</p></div><Badge variant="secondary">{DEMO_STATUSES.find(s=>s.value===d.status)?.label||d.status}</Badge></div>{d.url&&<a href={d.url} target="_blank" rel="noreferrer" className="mt-4 flex items-center gap-1 truncate text-sm text-primary hover:underline"><ExternalLink className="h-4 w-4"/>{d.url}</a>}<div className="mt-4"><Select value={d.status} onValueChange={value=>setStatus(d,value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{DEMO_STATUSES.map(s=><SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select></div>{d.prospect_id&&<Button variant="link" className="mt-2 h-auto p-0" asChild><Link to={`/menuvibes/prospects/${d.prospect_id}`}>Ver prospecto</Link></Button>}</CardContent></Card>)}</div>:<Card><CardContent className="flex flex-col items-center py-14 text-center"><Presentation className="mb-3 h-9 w-9 text-muted-foreground"/><p className="font-medium">No hay demos registradas</p><p className="text-sm text-muted-foreground">Vincula una referencia comercial a un prospecto.</p></CardContent></Card>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>Nueva demo</DialogTitle><DialogDescription>La demo lista es una referencia de venta; no publica ningún negocio.</DialogDescription></DialogHeader><div className="space-y-4 py-5"><div><Label>Prospecto *</Label><Select required value={form.prospect_id} onValueChange={v=>setForm(p=>({...p,prospect_id:v}))}><SelectTrigger className="mt-1"><SelectValue placeholder="Selecciona un restaurante"/></SelectTrigger><SelectContent>{prospects.map(p=><SelectItem key={getId(p)} value={getId(p)}>{p.business_name}</SelectItem>)}</SelectContent></Select></div>{[['slug','Identificador'],['url','URL de la demo'],['source_reference','Referencia de origen']].map(([k,l])=><div key={k}><Label>{l}</Label><Input className="mt-1" value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))}/></div>)}<div><Label>Estado</Label><Select value={form.status} onValueChange={v=>setForm(p=>({...p,status:v}))}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{DEMO_STATUSES.map(s=><SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>)}</SelectContent></Select></div><div><Label>Notas</Label><Textarea className="mt-1" value={form.notes} onChange={e=>setForm(p=>({...p,notes:e.target.value}))}/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button disabled={saving||!form.prospect_id}>{saving?'Guardando…':'Registrar demo'}</Button></DialogFooter></form></DialogContent></Dialog>
 </MenuVibesPage>;
};
